#!/usr/bin/env bash
# Copyright 2022 The Dusk Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script assumes it's parent directory is the repo root.
repo_path=$(dirname "$0")/..

cd "$repo_path"

if [[ $(git diff --stat) != '' ]]; then
    echo "Working tree is dirty, commit changes before attempting to roll DEPS"
    exit 1
fi

old_head=$(git rev-parse HEAD)

for i in $(find third_party -maxdepth 1 -mindepth 1 -type d); do
  name=`echo "${i%%/}" | cut -f2 -d'/' | tr '-' '_'`

  if [ "x${name}" == "xcpplint" ]; then
    continue
  fi

  roll-dep --ignore-dirty-tree --roll-to=origin/main "${i%%/}";
done

git rebase --interactive "${old_head}"
