title: Dusk
email: dsinclair@google.com
description: Dusk WebGPU Documentation
baseurl: "/Dusk"
url: "https://dj2.github.io"

highlighter: rouge

redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - strikethrough
    - with_toc_data
    - hard_wrap
    - no_styles
    - safe_links_only

collections:
  examples:
    output: true
